### ISSUE TITLE
Allow subpixel twiddling with keys 1-9

### ISSUE THREAD

**Issue by tomblench** [rawles/teletext-editor#14]
With a numeric keypad it makes more sense because the numbers are laid out in a 3x3 block and aren't character set dependent (for example, AZERTY)

**Comment by rawles** [comment]
Thanks for the suggestion. I've added it in 3a16dcf. Now, keys [7], [8], [4], [5], [1] and [2] twiddle subpixels. [9] clears all the subpixels. [6] fills all the subpixels. [3] inverts (‘reverses’) all the subpixels.
