### ISSUE TITLE
A command to hide the status bar.

### ISSUE THREAD

**Issue by rawles** [rawles/teletext-editor#15]
I've noticed that some users of the editor - @illarterate for example - sometimes save the canvas as a bitmap file to use elsewhere. With this in mind, we could have a command which temporarily hides the status bar so that it's not included in the screen grab. Would people find this useful?

**Comment by illarterate** [comment]
I would! I know the status bar can always be cropped out in an image editor, but it'd good to have the option.

**Comment by galaxxyz** [comment]
How about a "save as" command that generates an image?

**Comment by rawles** [comment]
@galaxxyz - In Firefox, you can right-click on the canvas and save its contents as a png.
@illarterate - I have something like this working now in the brance issue-15. You type ESC-0 (zero) to hide the status bar, and it reappears when you press a key or click the mouse. Is that the best solution or should I make it so that you can toggle the status bar on and off? The disadvantage of this is that you might end up editing without being able to see the status bar, but some people might prefer that.

**Comment by rawles** [comment]
By the way, the size of the canvas doesn't change when the status bar is hidden. Instead, it's just replaced by a black rectangle.

**Comment by illarterate** [comment]
Seeing as we (or rather I) have had compatibility issue with certain keyboards/systems in the past, a toggle button would be absolutely fantastic. ESC triggering still seems a bit dodgy on my Win8 system right now... gotta love Windows! ;)

**Comment by rawles** [comment]
Yeah, that's strange. I've never been able to reproduce that. I'll add something to the table on the left so that you'll be able to hide the status bar by clicking too. Right now I've implemented it such that it re-appears on any keyboard event. I think the combination of these should work for you.

**Comment by rawles** [comment]
This works with an additional feature. When you hide the status bar, the editor canvas gets resized and the underlying resolution changed so that a screenshot will come out looking much nicer.

**Comment by illarterate** [comment]
On-screen button working perfectly for me! I also like that you can export as GIF with or without character codes. Teacher always told me to 'show my working out'... ;)
