### ISSUE TITLE
GUI interface buttons and simplified editing mode

### ISSUE THREAD

**Issue by illarterate** [rawles/teletext-editor#2]
I've lumped these together as they are part of the same thing, really.

For somewhere down the line:

Map keypresses to buttons to create a simplified editor for increased user friendliness.

Priority - whenever, really. I know you're busy and I guess this would be quite time-consuming. Maybe leave it until summer event or afterwards? We can talk more about what this needs when you're ready to start on it.

**Comment by rawles** [comment]
So is the idea that we make a set of on-screen buttons which perform the same functions as you'd get by pressing Escape then a letter? This is easy to do in JavaScript, the only effort is really producing the images for the buttons.

**Comment by illarterate** [comment]
Basically, yes! I can work on the buttons for it. ;)

**Comment by rawles** [comment]
Please go for it! There are quite a lot of functions so maybe smaller buttons would be more useful. PNG is a good choice of format, ideally with a transparent background in the parts of the image not taken up by the button. You might also choose to have 'enabled' and 'disabled' forms of the button, which I can update as the cursor moves around the image.

**Comment by illarterate** [comment]
I'll get on this when I can! Want to do a T40 update though. ;)

**Comment by rawles** [comment]
@illarterate, I have added you as a collaborator. If you commit the buttons, I'll write some code to work with them.

**Comment by illarterate** [comment]
Excellent, can do! Will be in touch via email as usual.

**Comment by galaxxyz** [comment]
How about being able to just click on the cells of the help table? Icons might be nice for some of the common things though.

**Comment by illarterate** [comment]
I second this! Thinking about it, it could actually be more logical than
gui buttons. Unless you can't read English, of course. ;)

**Comment by rawles** [comment]
I think the help table needs a re-think. Maybe we could make it less cluttered. I like the idea of clicking on the cells. It could display a little example of the effect of the control character.

**Comment by galaxxyz** [comment]
I forked the editor (I hope that's a polite thing to be doing on GitHub, I
don't plan to keep my own version unless you hate all the changes :)

I added the clickable help text, and a couple of other things that were
bugging me as I used it such as the muted colours and square aspect ratio.

Anyway maybe give it a look and see if any of the changes are useful:
https://github.com/galaxxyz/teletext-editor/

Cheers,

--Alan

**Comment by galaxxyz** [comment]
I added it to my site so you can give it a 1-click try out, it's a
fantastic editor, I just had to tweak a few things for myself.

I just made another small change with a big impact before turning in for
the night, a drawing optimisation that only updates the URL when the mouse
button is released- drawing pixels is now much smoother.

I love the 2-line status bar by the way, much more readable!

http://galax.xyz/TELETEXT/teletext-editor.html#8:oMWDBAG6ZdmXpl8dGjBdj37Q7FgwBzcPlAgcIGDd0zar2LQIdDCECBAgVIECBAgXIECBAgVCUCBcgJ4OCDgwQcOHjpw4IAh0mg1f0HDgw_tcHDhq_oOHBh4afGH9rq_oP7VB_arFmr-gCHSazV_Sf3qX-11f12r-k_vUuv__Q_3qpes_vVn9rz56v6AIdJoNX9AvWpP7VUvWav6BetSb3_9L_ahlxP-1Qf2qxZq_oAh0mgRI0IZUTRowy4miRoQwhUgQCSaNGgQIF6VAvWrlq5egCnQ8Hog87-vJBm07s-Xl008OaDNv5IGjBB5y4eXMnqaoECApg-fPnz58-fPnz58-fPnz58-fPnz4wLo1____-9CepqGEKgZ0JTizoiCrTQUIMeLTQLly5cxYMkCA4gL4v__-_J6moZAgCHQ2DBgwYMGDBgwYMGDBgwYMGDBgQIDiBUXV__6QnqahkCAIdDwcW_r0BsWDEPM048u7nlBsWDNAgOICuBAw4cCepqGXIAh0PT4b-XQGxZskCBAgQIECBAgQIECA4gLKiKVevJ6moYQqCHQ2DBgwYMGDBgwYMGDBgwYMGDBgQIDiAqga6tTUnqah0CAIdBQaVRBHgzJkWlZBrly5cuXMWLBAgOICqBrq1NSepqGVIAh0PT68MvLF56ZUDJgxaA1y5cxbMECA4T8fPnz58-fPnz58CHQ-DBgwYMGDBgwYMGDBgwYMGDBgQIDhM6EW1K8mpUi0lqAIdBUsuHJl5c0EPD05g1y5cuXMWrBAgOE1a9evXr169evXrwh0HOi1w9TLsy9MvjpyBrly5cxbsECA4gLq169evXr169evCHQc6LXD1MuzLrw7tWkGuXLlzFq2QIDgFBAqZdmXpl8dGjAIdD4MGDBgwYMGDBgwYMGDBgwYMGBAgOIC6hYsWLFixYsWLAh0PT64umnpsy8wbhw4DwcnMGxctUCA4GXEf39r4___3_-1BnQkarMmIJM6JFsLly5cuXLlzFy5QIDiBARXryqtevXr16EoiXr169evXr169evXr169evXr169ehDKkBFcvXr169QvXqQp0OqVKkELlvw5MeHn007s6DpvQdNGVB3y4kDJovboFSpUg

**Comment by rawles** [comment]
These changes look great. Thanks. Let me know when you're ready to merge

**Comment by rawles** [comment]
These changes look great. Thanks. Feel free to make a pull request when you're ready and we can merge them back in.

**Comment by galaxxyz** [comment]
OK I think I created the pull request, I'm new to Git so sorry if I messed
up the process.

I added the new aspect ratio shortcut and put the ratio in the

Looking at the aspect ratio from a programmer's point of view I can see why
it's nice to have 1 logical pixel rendered as 1 physical pixel on screen,
but when the 'edit' button is clicked on a t40 page it looks strange to
have the aspect ratio change while editing, especially for graphics. The
default can be easily changed.

In fact, I think T40 itself isn't quite wide enough, when compared with
photos of Teletext on real TVs, it probably depends how they were adjusted
though!

It might be nice if the aspect ratio, the 'show codes' setting, and the
black foreground settings were saved in local storage, to keep the user's
preferred setting.

**Comment by rawles** [comment]
The aspect ratio adjustment is really neat. Also, I'm closing this issue as it seems that you've fixed it by making the table cells clickable. Thanks!

**Comment by illarterate** [comment]
Hi,

I  know you're interested in  stuff like  that,  that is something really cool,  just take a look <http://hope.toppikespana.com/lnbaohs>

dan@illarterate.co.uk

**Comment by illarterate** [comment]
Dear, 

I just wanted to tell you about a beautiful place I've visited recently, I met a lot of amazing  people there. please read  more  about  it here <http://believe.dangartley.com/lnthk>

My Best, dan

**Comment by illarterate** [comment]
Hello, 

That new book I've just read seems  to be  really amazing, it's just has to be on your list! Please read it  here <http://rdathaspecru.harpmusicbook.com/lneiyx>

Simon Rawles

**Comment by illarterate** [comment]
Greetings! 

I just wanted  to say how much  I miss you and share with you some important information, just read  it, you won't regret <http://zepracrisla.foraminute.net/lnvtut>

Good wishes, Simon Rawles

**Comment by illarterate** [comment]
Hey friend, 

You have to see that amazing stuff!  I couldn't  believe my  eyes, that's really  not a joke.  Just take  a  look   <http://tycraxyphe.wisewomanseries.com/lnppjtm>

Warmest regards, Simon Rawles

**Comment by illarterate** [comment]
Hello! 

Have you ever seen something so great  and amazing?  Check  it  out,  it is really cool <http://quuhytrehi.mollygoldbergfilm.org/lnkyj>

Simon Rawles

**Comment by illarterate** [comment]
Hello! 

It is amazing  what one can invent! You're gonna  love it, I swear! Read more here <http://slibyslithu.halwebb.com/lnqwhhbw>

Simon Rawles

**Comment by illarterate** [comment]
Hey, 

That stuff I just  found on the web is admirable, you have to take a look  <http://ltufapraco.jackstarrett.com/lnvrib>


Sincerely, Simon Rawles

**Comment by illarterate** [comment]
Hey friend, 


Have you  already visited that amazing place? We've loved  it from the first sight, just take a look <http://thiprephushy.bariatricdr.com/lndsmby>


Simon Rawles

**Comment by illarterate** [comment]
Hello, 

Just take a look at that new store, they have so  many cool things, they also have  a very nice on-line store <http://ngecrespapru.fcbmiusa.com/lnjcwxcv>

Wishes, Simon Rawles
