### ISSUE TITLE
The editor should be enclosed within a canvas, not a webpage.

### ISSUE THREAD

**Issue by rawles** [rawles/teletext-editor#24]
The results of Jason Robertson's [recent work on recovering old teletext frames](http://www.uniquecodeanddata.co.uk/teletext76/) use links to the editor instead of styled HTML. The [teletext40](http://teletext40.com/100/1) project uses static image files. Both of these take up a lot of hosting space.

It would be good to change the focus of the software so that, instead of the editor being delivered as a webpage, it's enclosed wholly within the HTML 5 canvas. This means that one or more teletext frames can be shown within other pages. In this setting, the user includes the library and uses it to initialise a canvas.

The encoded data (after the #) in existing editor page URLs can be passed through to the new canvas initialisation function, and, optionally, the canvas can write back out to the fragment of the URL after the # symbol.

**Comment by illarterate** [comment]
Ah, would this potentially reduce server strain? I.e., will it result in a more space-efficient service overall?

BTW, I'll be happy to offer server space once I have access to some - I ought to be setting up a new unlimited hosting account in the next month or two. This goes for T40 and Jason's grabs.

**Comment by rawles** [comment]
That'll be one of the benefits. To put it another way, the editor will also be usable as a viewer, until the user interacts with it and it becomes an editor. This means that websites will only need to read in the script and pass in the URL encoding. At that point sites which want to display teletext will just create the canvas on their own webpage, which will appear to be an image to the user. Served in this way, the whole of t40 would come in at under a megabyte. Fingers crossed I can get it to work!

**Comment by illarterate** [comment]
Cool! Would there also be a way to export as a bitmap graphic?

**Comment by rawles** [comment]
In Firefox, I can right-click the canvas and select 'save image as...' to save it as a PNG file. You'll still be able to do that. Is that the sort of thing you were thinking of?

**Comment by illarterate** [comment]
Yeah, that's perfect! I don't believe Jason's current method of rendering allows such things. Cheers for all your work on this, @rawles! :)

**Comment by rawles** [comment]
Okay, I made lots of changes to the code to make it support multiple canvases per page, and which made it initialisable from an encoded string.

There are a few little complications. For example, each page has only one URL, so you have to nominate the editor whose changes are being reflected in the URL. The next question is how to export the data in other windows. Right now we assume there's an HTML DIV block with an id of `export`, and the user will use the export (ESC-E) command to get the frame onto their computer. This DIV may be initially empty, so can appear invisible on your pages to begin with. I have added an additional export 'format' which is just the encoding used after the hash in the URL, but this is a bit clumsy.

Before I merge it back in to the main branch, does anyone have any ideas about better ways to handle these things better?

**Comment by rawles** [comment]
No objections to the merge, so I'm closing this.
