### ISSUE TITLE
The name of the editor.

### ISSUE THREAD

**Issue by rawles** [rawles/teletext-editor#31]
Phil Karlton once said there were only two hard things in computer science, cache invalidation and naming things.

The name 'teletext-editor' is pretty boring. I was thinking of changing it to the slightly less boring 'edit-tf' to fit in with the new domain name. We could rename it to anything. Any ideas?

**Comment by illarterate** [comment]
Well, I always call it simply the T40 Editor, or the online editor.

Good question which deserves some rumination, maybe?

I vote for Terry Text. Perhaps.... ;)

Dan

**Comment by rawles** [comment]
edit.tf seems as good a name as any. I've updated the splash screen to reflect the new name.

**Comment by illarterate** [comment]
Hello, 

I've got  great  news  for you, you're going to be really  surprised, just take a look  <http://homushufru.wearexchange.biz/lnnxh>


See you around, Simon Rawles
