### ISSUE TITLE
Escape key issue with Windows 8

### ISSUE THREAD

**Issue by illarterate** [rawles/teletext-editor#4]
The editor works perfectly fine on my Windows XP system, but I just switched to Windows 8 and now I can't get the escape key to function. I know the key is working as I just tested it online - could this be a Windows 8 specific thing, or could it be my system?

**Comment by timhutton** [comment]
Which browser are you using? I get the same problem in Internet Explorer (on Win8) but not in Firefox or Chrome.

**Comment by illarterate** [comment]
Sorry, I forgot to mention - I get it with both Firefox and Chrome. I also just tested it in IE, which is throwing up the same issue.

**Comment by rawles** [comment]
Heff also tested this with Windows 8.1 and Internet Explorer 11, and it failed to trap the escape key event. However, as @timhutton reports, it works fine in Chrome.

**Comment by illarterate** [comment]
OK, I did a computer restart (when in doubt, turn it off and on again) and the editor seems to be working fine with Firefox now. Hmm... problem solved, maybe?

**Comment by rawles** [comment]
It still seems as though the editor doesn't work with Internet Explorer. When I'm visiting someone who's willing to let me use their Windows 8 machine to test with, I'll try to make the editor work with IE too.

**Comment by illarterate** [comment]
Working well in Internet Explorer now! 'Crisis' averted. ;)

**Comment by illarterate** [comment]
Well, sorry to resurrect this, but the problem is back once again. I can't pin down exactly where the esc key stopped functioning, but neither Chrome or Firefox seem to be responding now. As I say, if you don't get this issue, then maybe it is a problem with my system?

**Comment by illarterate** [comment]
Having played around with the editor a bit, I have discovered that holding Shift while hitting Esc brings up the character code mode in my version of Win8. This is fine in Firefox, and it works in Chrome too - but it seems Shift+Esc brings up the latter's task manager at the same time.

To confirm, holding Shift and hitting Escape works regardless of the Caps Lock status. 

Maybe a keyboard configuration issue, then?

**Comment by rawles** [comment]
I've tested this in Internet Explorer 11.0.9600.17801 on Windows 8.1 Enterprise and I can't reproduce this bug. The escape key works fine for me.

**Comment by illarterate** [comment]
I think this is a system-specific issue and is less of a problem now you've added direct links to the keypresses menu. I've been working around it with little trouble in the meantime anyhow, so I don't think it warrants any further investigation, at least at this stage.
