### ISSUE TITLE
Clicking in table not working in firefox

### ISSUE THREAD

**Issue by ZXGuesser** [rawles/teletext-editor#44]
The code in this.keypress at line 1308 is causing an exception on Firefox 47.0.
I think because event is uninitialised at this point.

**Comment by illarterate** [comment]
I noticed this too. Seems to be the same in Chrome. Operating systems tested: Win10 & Win8.

**Comment by ZXGuesser** [comment]
the following seems to work in firefox (line 4329)

```
var fakepress = function(character) {
    if ( active_editor == null ) { return; } 

    active_editor.set_escape(1);
    event = new KeyboardEvent("keydown", {charCode : character.charCodeAt(0)});
    page_keypress(event);
}
```

**Comment by rawles** [comment]
Thanks for this fix. Apologies for the delay in applying it.

**Comment by galaxxyz** [comment]
Unfortunately this fix

**Comment by glxxyz** [comment]
Unfortunately this fix broke the "click on table" functionality for Chrome, in a different way. I've applied a fix that works for both Chrome and Firefox.

**Comment by rawles** [comment]
Seems to work nicely in Firefox and Safari on my system. Thanks!

**Comment by rawles** [comment]
Works on my version of Safari (9.0.2).
