### ISSUE TITLE
Cut and paste

### ISSUE THREAD

**Issue by rawles** [rawles/teletext-editor#47]
I've often wanted to copy a line to another line lower down the frame. Other people have mentioned that cut and paste would be useful. It would be pretty easy to implement.

I'd just like opinions on how the area should be selected and pasted. Should selection be like in a word processor, running along with the text, or should the area be a rectangle (or even some other shape)? Secondly, when you paste the clipboard, should it overwrite what's there or insert the text before it? Because of all those character codes, things might end up pretty messy.

Another alternative is to use the BBC micro's COPY key. In this mode you would move a copy-cursor to somewhere else on the screen, and each press of COPY would copy its contents to the current editing cursor, and advance both.

Any or all of these are easy enough to implement. What do people think they'd like most?

**Comment by ZXGuesser** [comment]
The BBC micro style copy key sounds like a good idea to me, though I can see it being confusing to anyone who never used a beeb.
I think overwriting rather than inserting on paste since inserting isn't generally much use anyway as far as I'm concerned since stuff ends up shoved off the line into the void. Maybe you could have it toggle-able between insert and overwrite paste mode.

**Comment by rawles** [comment]
Hi, I'm working on a cut and paste using rectangle/block selection for cut, and overwrite for paste over in branch 'issue-47'. You select the area with escape and then either the arrow keys or mouse to drag out the rectangle. You will then be able to copy and paste it. Coming soon!

**Comment by rawles** [comment]
I've just merged this in. Not sure if everyone else likes how it works in the user interface. Let me know if you don't.

**Comment by rawles** [comment]
I had to change a few keys around but I don't think it'll affect people too much.
