### ISSUE TITLE
Right-clicking on the canvas causes a mouse click

### ISSUE THREAD

**Issue by rawles** [rawles/teletext-editor#51]
In Firefox, and probably other browsers, when you right-click on the canvas you can save the image to a PNG file. Annoyingly, this causes a mouse click, which can invert a pixel, or whatever. The editor should be able to detect and ignore these.

**Comment by Horsenburger** [comment]
That’s pretty cool, I’ve been copy and pasting into photoshop, this is easier.

**Comment by rawles** [comment]
Fixed.
