### ISSUE TITLE
Command Key in Firefox on Mac does not work

### ISSUE THREAD

**Issue by hairydalek** [rawles/teletext-editor#54]
Muscle memory makes me use Command + W to close browser tabs or windows (or, indeed windows in most apps). However, if Edit.TF is running, Command does not work, and I get a W on the canvas at the cursor position.

**Comment by rawles** [comment]
The editor disables the default effect of key combinations like this. When you say 'when edit.tf is running', do you mean that when it's in the active tab, or in any tab, or in another window, ...?

**Comment by hairydalek** [comment]
It's when it's the current active tab.

The Command key in the Mac is very important. Users use that in favour of accessing the menu, so o if Edit-tf is running in the current tab, I can't use Command+N to create a new window, or Command+T to create a new tab, or Command+W to close the tab or window. It disables every keyboard shortcut for menu items, which isn't good.

**Comment by rawles** [comment]
I can't reproduce this on my system. In Firefox 49.0.2, OS X El Capitan, when I bring up the editor and press Command-N, whether edit.tf is in the current tab or not, a new window appears. Command-W also closes tabs and windows.

**Comment by hairydalek** [comment]
Just checked my version of Firefox. It was supposed to be auto updating, but it hadn't. So now on 49.0.2 in Sierra, and things work as you describe.
