### ISSUE TITLE
No White Text

### ISSUE THREAD

**Issue by pjfdirect** [rawles/teletext-editor#64]
It seems like the implicit white text colour at the beginning of a line is killed if I first set the line to some other colour and then delete the colour code. See video:

https://m.beeble.tv/tmp19r/default-text.mp4

**Comment by rawles** [comment]
Firstly, thanks for an excellent bug report, with video and everything! Very nice. The problem was that I'd defined the default foreground colour for a line incorrectly. It's fixed now, so I'm closing the bug. Please re-open if you still have the problem.
