### ISSUE TITLE
Grid Click Order

### ISSUE THREAD

**Issue by pjfdirect** [rawles/teletext-editor#68]
Could the full grid be made the result of the first click after the default?

![image](https://cloud.githubusercontent.com/assets/23056210/23587252/ddc3b43e-019f-11e7-83ed-43587d21a8e5.png)

(the cursor position in the illustration is not significant, pls ignore :)

**Comment by rawles** [comment]
The editor now starts off with the subtle lines showing the extent of a broadcast teletext frame, then it changes to full, and finally blank. I think this is the best order, just to reinforce to people that for teletext - the application that most people seem to have in mind - some areas of the screen are to some extent off-limits. Anyway, I hope you prefer the change.

**Comment by pjfdirect** [comment]
sounds sound to me :D thanks!

**Comment by pjfdirect** [comment]
works a treat! thanks again ^_^
