### ISSUE TITLE
Viewdata output

### ISSUE THREAD

**Issue by jbrooksuk** [rawles/teletext-editor#7]
Is it possible to get the result, but in a Viewdata format?

**Comment by rawles** [comment]
Thanks for this. Yes, the export of data in various formats (of which viewdata is one) is something that should definitely be in the editor. I was thinking about how this would be best done. Maybe if we had a new command that popped up a set of links, each of which is a [data URI](https://en.wikipedia.org/wiki/Data_URI_scheme) containing the data in a commonly-used format, for compatibility with viewdata and other editors. How does that sound?

**Comment by rawles** [comment]
A way to do frame export has been requested again. I think we should work on this issue next.

**Comment by jbrooksuk** [comment]
:+1: that'd be awesome!

**Comment by rawles** [comment]
Hi @jbrooksuk - I've made the script that I use for conversion, `url2raw.pl`, available. For this bug I intend to let you save to a file in the editor, but until I get around to doing that, the script may provide a way to do it. Instructions are in the script itself - if you have problems please open an issue and I'll do my best to help.

**Comment by jbrooksuk** [comment]
Awesome! Thanks :)

**Comment by rawles** [comment]
I'm working on this now, in the 'output' branch. You press ESC-e (for 'export'), and a small box appears with a choice of formats. Each one is a link to a data URI, which you can download directly. This means at no point does the server store your page. When you move the cursor, the box disappears. This is a bit too cautious, really. It should disappear on any page edit, but it works just as well.

At the moment, the only format is the raw data, but I'm getting help from @peterkvt80 to implement TTI format, for interoperability with his wxTED editor.

**Comment by illarterate** [comment]
Hi, 

After a  month of  journey I went back home, it  was  a lovely journey, take a look at some photos of it  <http://rdufefuphi.sheji114.com/lnanxeg>


Warmly, Simon Rawles
